language: cpp
sudo: false
dist: xenial

compiler:
- clang
- gcc

addons:
  postgresql: "9.5"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - clang-5.0
    - cpp-6
    - flex
    - gcc-6
    - g++-6
    - libpq-dev
    - libpq5
    - libstdc++6
    - libtool
    - pkg-config
    - clang-format-5.0
    - pandoc
    - perl
    - parallel

script: ./travis-build.sh

cache:
  directories:
  - $HOME/.ccache
  - .libs

notifications:
  email: false
branches:
 only:
 - master 

